Задание 1

In [51]:
import numpy as np
a = np.array([i for i in range(12,24)])
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

Задание 2

In [52]:
a1 = np.reshape(np.ravel(a), (2, 6))
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [53]:
a2 = np.reshape(np.ravel(a), (3, 4))
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [54]:
a3 = np.reshape(np.ravel(a), (4, 3))
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [55]:
a4 = np.reshape(np.ravel(a), (6, 2))
a4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [56]:
a5 = np.reshape(np.ravel(a), (12, 1))
a5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

Задание 3

In [57]:
a6 = np.reshape(a, (3,-1))
a6

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [58]:
a7 = np.reshape(a, (4,-1))
a7

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [59]:
a8 = np.reshape(a, (6,-1))
a8

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [60]:
a9 = np.reshape(a, (-1,4))
a9

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [61]:
a10 = np.reshape(a, (-1,3))
a10

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

Задание 4
Нет, так как 



In [62]:
a5.ndim

2

Задание 5

In [64]:
a = np.random.randn(3, 4)
a

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986],
       [-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975]])

In [65]:
b = a.flatten()
b

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337,
       -0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004,
       -0.46341769, -0.46572975])

In [66]:
a.size == b.size

True

Задание 6

In [ ]:
a = np.array([i for i in range(20,0,-2)])
a

Задание 7

In [69]:
b = np.arange(20, 1, -2)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

 Разницы никакой между массивами

Задание 8

In [71]:
a = np.zeros((3, 2))
b = np.ones((2, 2))

In [72]:
v = np.concatenate((a, b), axis = 0)
v

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

In [73]:
v.size

10

Задание 9

In [75]:
a = np.arange(0, 12)
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [76]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [77]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [78]:
B.shape

(4, 4)

In [79]:
np.linalg.det(B) == 0

True

Обратной матрицы не существует, так как определитель равен 0

Задание 10,11

In [88]:
np.random.seed(42)
c = np.random.randint(0, 16, 16)
C = c.reshape((4, 4))
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

Задание 12

In [90]:
D = 10 * C + B
print(D)

[[ 65  44 143 172]
 [114 120 206 162]
 [ 83 176 169 272]
 [132 222 282 342]]


In [91]:
np.linalg.det(D)

-28511999.999999944

In [92]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

In [93]:
np.linalg.matrix_rank(D) 

4

Задание 13

In [94]:
D_inv[D_inv>0] = 1
D_inv[D_inv<0] = 0
D_inv

array([[1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.]])

In [95]:
E = np.where(D_inv, B, C)
E

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])